<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="SkiaSharp" Version="2.88.8" />
    <PackageVersion Include="Silk.NET.Windowing" Version="2.21.0" />
    <PackageVersion Include="Silk.NET.OpenGL" Version="2.21.0" />
    <PackageVersion Include="Silk.NET.Input" Version="2.21.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>
</Project>
