<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeepSpaceSaga.Contracts\DeepSpaceSaga.Contracts.csproj" />
    <ProjectReference Include="..\DeepSpaceSaga.Motion\DeepSpaceSaga.Motion.csproj" />
    <ProjectReference Include="..\DeepSpaceSaga.Engine.LocalClient\DeepSpaceSaga.Engine.LocalClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.OpenGL" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Images\Cursors\cursor-selected.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\Cursors\cursor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\UI\GameSessionScreenUI\title-bar\" />
    <Folder Include="UI\Screens\" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DeepSpaceSaga.Client.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="gameinfo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\common.close.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\common.close.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\load.delete.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\load.delete.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\load.load.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\load.load.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\common.close.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\common.close.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.delete.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.delete.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.new.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.new.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.overwrite.active.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\save.overwrite.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.accelerate.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.accelerate.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.brake.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.brake.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.maintainCourse.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.maintainCourse.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.maintainSpeed.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.maintainSpeed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.orbit.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.orbit.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.speedSynchronization.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.speedSynchronization.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.directionSynchronization.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.directionSynchronization.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\navigation.dock.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\navigation.dock.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\navigation.stationsList.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\navigation.stationsList.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\scanner.generalScan.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\scanner.generalScan.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\scanner.structuralScan.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\scanner.structuralScan.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnLeftStep.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnLeftUntilCancel.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnLeftUntilCancel.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnLeftStep.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnRightStep.active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnRightUntilCancel.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\engine.turnRightStep.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\module-panel-caption-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\module-panel-body-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\title-bar\title-bar-button-hide.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\title-bar\title-bar-button-show.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\command-panel-caption-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\mechanics-window-background-titlebar-1400x900.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\mechanics-window-background-titlebar-1700x1200.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Commands\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Modules\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scenarios\Default\scenario.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scenarios\Default_500\scenario.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameLoadScreen\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSaveScreen\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
