<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeepSpaceSaga.Contracts\DeepSpaceSaga.Contracts.csproj" />
    <ProjectReference Include="..\DeepSpaceSaga.Motion\DeepSpaceSaga.Motion.csproj" />
    <ProjectReference Include="..\DeepSpaceSaga.Engine.LocalClient\DeepSpaceSaga.Engine.LocalClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.OpenGL" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Images\Cursors\cursor-selected.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\Cursors\cursor.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\navigation-panel\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\UI\GameSessionScreenUI\title-bar\" />
    <Folder Include="UI\Screens\" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DeepSpaceSaga.Client.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="gameinfo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-accelerate-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-accelerate.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-brake-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-brake.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-maintain-course-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-maintain-course.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-maintain-speed-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-maintain-speed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-orbit-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-engine-orbit.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-navigation-dock-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-navigation-dock.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-navigation-stations-list-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-navigation-stations-list.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-scanner-general-scan-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-scanner-general-scan.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-scanner-structural-scan-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-scanner-structural-scan.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-left-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-left-continuous-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-left-continuous.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-left.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-right-active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-right-continuous.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\commands-panel\command-panel-button-turn-right.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\module-panel-caption-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\module-panel-body-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\title-bar\title-bar-button-hide.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\title-bar\title-bar-button-show.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Images\UI\GameSessionScreenUI\command-panel-caption-background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Commands\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scenarios\Default\scenario.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scenarios\Default_500\scenario.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
